version: "3.4"
services:
  varnish:
    environment:
      DNSDOCK_ALIAS: webservers.local
    image: varnish:6.0.3
    dns: 172.17.0.1
    network_mode: bridge
    volumes:
      - "./containers/varnish/default.vcl:/etc/varnish/default.vcl:ro"
    links:
      - web
  web:
    environment:
      DNSDOCK_ALIAS: webservers.web.local
    dns: 172.17.0.1
    network_mode: bridge
    image: nginx:latest
    volumes:
      - "./html:/var/www/html"
      - "./containers/nginx/site.conf:/etc/nginx/conf.d/default.conf"
    links:
      - php
  php:
    environment:
      DNSDOCK_ALIAS: webservers.php.local
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=webservers.local
    dns: 172.17.0.1
    network_mode: bridge
    build: "./containers/php"
    volumes:
      - "./www:/var/www"
  dnsdock:
    environment:
      DNSDOCK_ALIAS: dnsdock.local
    image: tonistiigi/dnsdock
    network_mode: bridge
    ports:
    - 172.17.0.1:53:53/udp
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  mailcatcher:
    environment:
      DNSDOCK_ALIAS: mailcatcher.local
    image: schickling/mailcatcher
    network_mode: bridge
  mysql:
    environment:
      DNSDOCK_ALIAS: webservers.mysql.local
      MYSQL_PASSWORD: mage
      MYSQL_USER: mage
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: docker
    image: mysql:5.7
    dns: 172.17.0.1
    network_mode: bridge
    volumes:
    - "./data/mysql:/var/lib/mysql"
  es:
    environment:
      DNSDOCK_ALIAS: webservers.es.local
    dns: 172.17.0.1
    network_mode: bridge
    build: "./containers/es"
    volumes:
    - "./data/es:/usr/share/elasticsearch/data"
  kibana:
    image: kibana:4.6.6
    links: 
      - es
    dns: 172.17.0.1
    network_mode: bridge
    environment:
      DNSDOCK_ALIAS: webservers.kibana.local
      ELASTICSEARCH_URL: http://webservers.es.local:9200
  redis:
    image: redis
    dns: 172.17.0.1
    network_mode: bridge
    environment:
      DNSDOCK_ALIAS: webservers.redis.local
    volumes:
      - "./data/redis:/var/lib/redis"
    command: ["redis-server", "--appendonly", "yes"]
  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    dns: 172.17.0.1
    network_mode: bridge
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - DNSDOCK_ALIAS=webservers.mq.local
