---
webservers:
  environment:
    DNSDOCK_ALIAS: webservers.local
    XDEBUG_CONFIG: remote_host=172.17.0.1
  dns: 172.17.0.1
  build: "./php"
  volumes:
  - "./html/:/var/www/html"
  container_name: webservers
phpmyadmin:
  environment:
    DNSDOCK_ALIAS: phpmyadmin.local
    PMA_HOST: mysql.local
    PMA_USER: root
    PMA_PASSWORD: docker
  image: phpmyadmin/phpmyadmin
  dns: 172.17.0.1
  container_name: phpmyadmin
dnsdock:
  environment:
    DNSDOCK_ALIAS: dnsdock.local
  image: tonistiigi/dnsdock
  ports:
  - 172.17.0.1:53:53/udp
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
  container_name: dnsdock
mailcatcher:
  environment:
    DNSDOCK_ALIAS: mailcatcher.local
  image: schickling/mailcatcher
  container_name: mailcatcher
mysql:
  environment:
    DNSDOCK_ALIAS: mysql.local
    MYSQL_PASSWORD: mage
    MYSQL_USER: mage
    MYSQL_DATABASE: magento
    MYSQL_ROOT_PASSWORD: docker
  image: mysql:5.6
  dns: 172.17.0.1
  volumes:
  - "./data/mysql:/var/lib/mysql"
  container_name: mysql
