---
webservers:
  environment:
    DNSDOCK_ALIAS: webservers.local
    XDEBUG_CONFIG: remote_host=172.17.0.1
  dns: 172.17.0.1
  build: "./php"
  volumes:
  - "./html/:/var/www/html"
dnsdock:
  environment:
    DNSDOCK_ALIAS: dnsdock.local
  image: tonistiigi/dnsdock
  ports:
  - 172.17.0.1:53:53/udp
  volumes:
  - "/var/run/docker.sock:/var/run/docker.sock"
mailcatcher:
  environment:
    DNSDOCK_ALIAS: mailcatcher.local
  image: schickling/mailcatcher
mysql:
  environment:
    DNSDOCK_ALIAS: mysql.local
    MYSQL_PASSWORD: mage
    MYSQL_USER: mage
    MYSQL_DATABASE: magento
    MYSQL_ROOT_PASSWORD: docker
  image: mysql:5.6
  dns: 172.17.0.1
  volumes:
  - "./data/mysql:/var/lib/mysql"
