--- 
dnsdock: 
  command: "-domain=\"local\""
  container_name: dnsdock
  environment: 
    DNSDOCK_ALIAS: dnsdock.local
  image: tonistiigi/dnsdock
  ports: 
    - "172.17.0.1:53:53/udp"
  volumes: 
    - "/var/run/docker.sock:/var/run/docker.sock"
mailcatcher: 
  container_name: mailcatcher
  environment: 
    DNSDOCK_ALIAS: mailcatcher.local
  image: schickling/mailcatcher
mysql: 
  container_name: mysql
  dns: "172.17.0.1"
  environment: 
    DNSDOCK_ALIAS: mysql.local
    MYSQL_DATABASE: magento
    MYSQL_PASSWORD: mage
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_USER: mage
  image: "mysql:5.6"
  volumes: 
    - "./data/mysql:/var/lib/mysql"
phpmyadmin: 
  container_name: phpmyadmin
  dns: "172.17.0.1"
  environment: 
    DNSDOCK_ALIAS: phpmyadmin.local
    PMA_HOST: mysql.local
    PMA_PASSWORD: docker
    PMA_USER: root
  image: phpmyadmin/phpmyadmin
webservers: 
  build: ./php
  container_name: webservers
  dns: "172.17.0.1"
  environment: 
    DNSDOCK_ALIAS: webservers.local
    XDEBUG_CONFIG: remote_host=172.17.0.1
  volumes: 
    - "./html/:/var/www/html"
