php:
  build: ./php
  container_name: webservers
  dns: 172.17.0.1
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
  volumes:
    - ./html/:/var/www/html

mysql:
  image: mysql:5.5
  container_name: mysql
  dns: 172.17.0.1
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_USER: mage
    MYSQL_PASSWORD: mage
    MYSQL_DATABASE: magento
  volumes:
    - ./data/mysql:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  dns: 172.17.0.1
  environment:
    PMA_USER: root
    PMA_PASSWORD: docker
    PMA_HOST: mysql.docker

mailcatcher:
  image: schickling/mailcatcher
  container_name: mailcatcher

dns:
  image: phensley/docker-dns
  ports:
    - "172.17.0.1:53:53/udp"
  volumes:
    - "/var/run/docker.sock:/docker.sock"
