webservers:
  build: ./php
  container_name: webservers
  dns: 172.17.0.1
  environment:
    XDEBUG_CONFIG: remote_host=172.17.0.1
    DNSDOCK_ALIAS: webservers.local
  volumes:
    - ./html/:/var/www/html

mysql:
  image: mysql:5.6
  container_name: mysql
  dns: 172.17.0.1
  environment:
    MYSQL_ROOT_PASSWORD: docker
    MYSQL_USER: mage
    MYSQL_PASSWORD: mage
    MYSQL_DATABASE: magento
    DNSDOCK_ALIAS: mysql.local
  volumes:
    - ./data/mysql:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  dns: 172.17.0.1
  environment:
    PMA_USER: root
    PMA_PASSWORD: docker
    PMA_HOST: mysql.local
    DNSDOCK_ALIAS: phpmyadmin.local

mailcatcher:
  image: schickling/mailcatcher
  container_name: mailcatcher
  environment:
    DNSDOCK_ALIAS: mailcatcher.local

dnsdock:
  image: tonistiigi/dnsdock
  container_name: dnsdock
  command: -domain="local"
  ports:
    - "172.17.0.1:53:53/udp"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  environment:
    DNSDOCK_ALIAS: dnsdock.local
