version: "3.5"

networks:
  web:
    external: true

services:
  traefik:
    image: "traefik:v2.3"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "3306:3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./containers/traefik/certs:/certs:ro"
      - "./containers/traefik/traefik.yml:/traefik.yml:ro"
      - "./containers/traefik/dynamic.yml:/dynamic.yml:ro"
    networks:
      web:
        aliases:
          - magento.local
  mailcatcher:
    image: schickling/mailcatcher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailcatcher.rule=Host(`mailcatcher.local`)"
      - "traefik.http.routers.mailcatcher.entrypoints=web"
      - "traefik.http.services.mailcatcher.loadbalancer.server.port=1080"
    hostname: mailcatcher.local
    networks:
      web:
        aliases:
          - mailcatcher.local
  varnish:
    image: varnish:6.0.3
    hostname: magento.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.varnish.rule=Host(`goldapple.local`)"
      - "traefik.http.routers.varnish.entrypoints=websecure"
      - "traefik.http.routers.varnish.tls=true"
    networks: 
      - web
    volumes:
      - "./containers/varnish/default.vcl:/etc/varnish/default.vcl:ro"
    depends_on:
      - web
  web:
    image: nginx:latest
    networks:
      - web
    volumes:
      - "./www/html:/var/www/html"
      - "./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
  php:
    build: "./containers/php"
    container_name: "magento_php_1"
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      PHP_IDE_CONFIG: serverName=magento.local
    networks: 
      - web
    volumes:
      - "./www:/var/www"
      -  "/usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro"
  mysql:
    environment:
      MYSQL_PASSWORD: mage
      MYSQL_USER: mage
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: docker
    image: mysql:5.7
    hostname: magento.mysql.local
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
      - "traefik.tcp.services.mysql.loadbalancer.server.port=3306"
    networks:
      web:
        aliases:
          - magento.mysql.local
    volumes:
      - "./data/mysql:/var/lib/mysql"
  es:
    environment:
      - discovery.type=single-node
    build: "./containers/es"
    hostname: magento.es.local
    networks:
      web:
        aliases:
          - magento.es.local
    volumes:
      - "./data/es:/usr/share/elasticsearch/data"
  redis:
    image: redis:5-buster
    hostname: magento.redis.local
    networks:
      web:
        aliases:
          - magento.redis.local
    volumes:
      - "./data/redis:/data"
    command: ["redis-server", "--appendonly", "yes"]
  rabbit:
    environment:
      RABBITMQ_DEFAULT_USER: mage
      RABBITMQ_DEFAULT_PASS: mage
    image: rabbitmq:3.8-management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbit.rule=Host(`magento.rabbit.local`)"
      - "traefik.http.routers.rabbit.entrypoints=web"
      - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
    hostname: magento.rabbit.local
    networks:
      web:
        aliases:
          - magento.rabbit.local
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    hostname: magento.zookeeper.local
    networks:
      web:
        aliases:
          - magento.zookeeper.local
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - "./data/zookeeper:/var/lib/zookeeper"
  ofelia:
    image: mcuadros/ofelia:latest
    networks: 
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./containers/ofelia/config.ini:/etc/ofelia/config.ini"
