entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  mysql:
    address: :3306

providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    network: web
    exposedByDefault: false
  file:
    filename: /dynamic.yml
    watch: false

api:
  dashboard: true
  insecure: false
  debug: false

log:
  level: INFO
accessLog: true
